In [3]:
import numpy as np

In [52]:
#collec data

x = np.array([[0,0,1],
            [0,1,1],
            [1,0,1],
            [1,1,1]])

y = np.array([[0],
             [1],
             [1],
             [0]])
print ('x:')
print (x)
print ()
print('y:')
print (y)

x:
[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]

y:
[[0]
 [1]
 [1]
 [0]]


In [64]:
#build mordel

num_epochs = 60000

# initialize weights
syn0 = 2 * np.random.random(tuple(reversed(x.shape))) - 1
syn1 = 2 * np.random.random(y.shape) - 1

print ("syn0")
print (syn0)
print ()
print ('sys1')
print (sys1)

syn0
[[-0.25256988  0.4029003  -0.67063056  0.31961976]
 [-0.10581503 -0.01388947  0.13625314  0.89657581]
 [-0.91653051 -0.33455709  0.44236435 -0.53469391]]

sys1
[[ 0.2798216 ]
 [ 0.71506016]
 [ 0.53760987]
 [ 0.00805324]]


In [61]:
def nonlin(x,deriv=False):
    if (deriv==True):
        return x*(1-x)
    
    return 1/(1+np.exp(-x))

In [66]:
#Train model
for j in range(num_epochs):
    #feed forward through layers 0,1, and 2
    l0 = x # input layer
    l1 = nonlin(np.dot(l0,syn0)) # input layer to first layer
    l2 = nonlin(np.dot(l1,syn1)) # first layer to output layer
    
    #how much did we miss the target value?
    l2_error = y - l2
    
    if (j%10000) == 0:
        print ("Error:"+ str(np.mean(np.abs(l2_error))))
    
    #in what direction is the target value?
    l2_delta = l2_error * nonlin(l2,deriv=True)
    
    #how much did each l1 value contribute to l2 error
    l1_error = l2_delta.dot(sys1.T)
    
    l1_delta = l1_error * nonlin(l1,deriv=True)
    
    
    syn1 += l1.T.dot(l2_delta)
    syn0 += l0.T.dot(l1_delta)

Error:0.500193564178
Error:0.0196383008249
Error:0.0131198054332
Error:0.010463388462
Error:0.0089375825827
Error:0.00791934169501
